apiVersion: v1
kind: PersistentVolume
metadata:
 name: staticpv
spec:
 capacity:
   storage: "20Gi"
 accessModes:
   - ReadWriteMany
 nfs:
   server: "fsf-dal1001b-fz.adn.networklayer.com"
   path: "/IBM02SEV1186049_766/data01"
