kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: staticpvc
 annotations:
   volume.beta.kubernetes.io/storage-class: ""
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: "20Gi"
