kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: retain-pvc #testclaimname # user can choose any name as per kubernetes
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-file-retain-bronze" # name of the class which was created by using class.yaml file
spec:
  accessModes:
    - ReadWriteMany # access mode
  resources:
    requests:
      storage: 20Gi #
